### PR TITLE
ci(pre-commit): Enable pre-commit CI and renovate

### PR DESCRIPTION
**Pull request by hofbi**
Since the rules already prvide a pre-commit config, we should also make sure the checks pass CI and hooks stay up to date.

### CODE REVIEW

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
@alexeagle

**Review by alexeagle — APPROVED** [review]
I think it looks good, but let's land your bazel-lib usage of it and get a few days usage to verify it behaves how rules authors will want, before we update the template.

**Comment by hofbi** [comment]
> I think it looks good, but let's land your bazel-lib usage of it and get a few days usage to verify it behaves how rules authors will want, before we update the template.

Sounds good. I pushed another commit fixing all pre-commit issues so that we can merge in a few days.

**Comment by hofbi** [comment]
@alexeagle Having this merged in https://github.com/bazel-contrib/bazel-lib for a week seems to work. Should we add this to the template as well?

**Comment by alexeagle** [comment]
Yes, SGTM thanks for following up.

**Pull request merged**
