### PR TITLE
chore: break out a reusable GitHub Actions workflow

### PR DESCRIPTION
**Pull request by alexeagle**
This will allow downstream forked repos to get improvements to the copy they got from here.

### CODE REVIEW

**Comment by alexeagle** [comment]
Example usage downstream: https://github.com/aspect-build/rules_jasmine/pull/50

**Comment by alexeagle** [comment]
I guess it's not desirable that you end up with a copy of the reusable workflow in a repo that's stamped out from this template, so there ought to be a separate repository under bazel-contrib that has the reusable workflow file and gets tagged.

Technically it could go in https://github.com/bazel-contrib/.github but it seems strange for that repo to be tagged.
I could make a new repo, but I wish we wouldn't have the overhead of configuring one just for a single file.
We could use some other repo like SIG-rules-authors, but it seems a waste for users to clone that whole thing to get a single file.

**Comment by kormide** [comment]
> I guess it's not desirable that you end up with a copy of the reusable workflow in a repo that's stamped out from this template, so there ought to be a separate repository under bazel-contrib that has the reusable workflow file and gets tagged.

I'm not quite following this. It's not desirable to get this workflows ci template?

**Comment by alexeagle** [comment]
@kormide the idea is that the reusable workflow is centrally updated, so every repo doesn't end up having to maintain a forked copy of it.

**Review by kormide — APPROVED** [review]

**Pull request merged**
